# Generated by Django 5.2.6 on 2025-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('link_doacao', models.URLField(blank=True, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
